name: Generate ASCII

on: push

jobs:
    build_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v6

            - name: Install cowsay
              run: |
                sudo apt-get install cowsay -y

            - name: Execute cowsay
              run: |
                cowsay -f dragon "Run for cover, I am a DRAGON" > dragon.txt

    test_job:
        runs-on: ubuntu-latest
        steps:
            - name: Test file exists
              run: |
                grep -i dragon dragon.txt

    deploy_job:
        runs-on: ubuntu-latest
        steps:
            - name: Read file
              run: |
                cat dragon.txt 
            - name: Deployment
              run: echo "Deploying..."              
