name: Matrix

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
                os: ["ubuntu-latest", "ubuntu-22.04", "windows-latest"]
                image: ["hello-world", "alpine"]
                exclude:
                  - image: alpine
                    os: windows-latest
                include:
                  - image: amd64/alpine
                    os: ubuntu-22.04
        runs-on: ${{ matrix.os }}
        steps:
            - name: Run on ${{ matrix.os }}
              run: docker run ${{ matrix.image }}