name: Matrix

on:
    push:
    workflow_dispatch:

jobs:
    deploy:
        strategy:
            matrix:
                os: ["ubuntu-latest", "ubuntu-20.04", "windows-latest"]
                image: ["hello-world", "alpine"]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Run on ${{ matrix.os }}
              run: docker run ${{ matrix.image }}